unit TestClasse;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.dateutils, Classe.Pessoa, System.SysUtils;

type
  // Test methods for class TPessoa

  TestTPessoa = class(TTestCase)
  strict private
    FPessoa: TPessoa;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestImpostoRenda;
  end;

implementation

procedure TestTPessoa.SetUp;
begin
  FPessoa := TPessoa.Create;
end;

procedure TestTPessoa.TearDown;
begin
  FPessoa.Free;
  FPessoa := nil;
end;

procedure TestTPessoa.TestImpostoRenda;
var
  ReturnValue: Double;
  ASalario: Double;
begin
  ASalario := 900;
  // TODO: Setup method call parameters
  ReturnValue := FPessoa.ImpostoRenda(ASalario);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPessoa.Suite);
end.

